### ISSUE TITLE
Circular aperture formula discrepancy?

### ISSUE THREAD

**Issue by mb2448** [hablabx/hci_noise#1]
In coronagraph_routines.pro, the following lines are used often to essentially compute the area of a circular aperture:

    ;      X - diameter or length of photometric aperture (lambda/D)
    ;      T - system throughput
    ;    lam - wavelength (um)
    ;   dlam - spectral element width (um)
    ;      D - telescope diameter (m)

    IF KEYWORD_SET(circ)  THEN Omega = !DPI*(X*lam*1.d-6/D*180.*3600./!DPI)^2. ; circular aperture size (arcsec**2)
    IF ~KEYWORD_SET(circ) THEN Omega = 4.d0*(X*lam*1.d-6/D*180.*3600./!DPI)^2. ; square aperture size (arcsec**2)

Here `X` is indicated in the docstring as being the **diameter or length**, but that doesn't seem consistent with the formulae as

_A = pi/4*(X lambda/D * 180/pi*3600)^2_ (circle, A=pi d^2/4)
_A = (X lambda/D * 180/pi*3600)^2_ (square, A = d^2)

Using the italicized formulae above gives answers consistent with what is in Robinson 2016, Section 3, at least for czodi (have not checked others yet).  Using the formulae as implemented in the code, and taking `X` as the **diameter** (as indicated), gives answers off by a factor of ~4 from Robinson.  So it seems either `X` should be indicated in the docstring as **radius**, or the italicized formulae should be used.

**Comment by tdrobinson** [comment]
Thanks for catching this, Michael!  I have updated the code comments to indicate that X is the photometric aperture _radius_.
